
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: snapshots.backupdriver.io
spec:
  group: backupdriver.io
  names:
    kind: Snapshot
    listKind: SnapshotList
    plural: snapshots
    singular: snapshot
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ' Snapshot is used to request that a snapshot is taken.  It is
        not used to manage the inventory of snapshots and does not  need to exist
        in order to clone the resource from a snapshot'
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec is the custom resource spec
          properties:
            backupRepository:
              description: The backup repository to snapshot into.  The namespace
                the Snapshot/PVC lives in must have access to the repository
              type: string
            resourceHandle:
              description: ResourceHandle refers to a Kubernetes resource, currently
                a PVC but this may be extended in the future
              properties:
                apiGroup:
                  description: APIGroup is the group for the resource being referenced.
                    If APIGroup is not specified, the specified Kind must be in the
                    core API group. For any other third-party types, APIGroup is required.
                  type: string
                kind:
                  description: Kind is the type of resource being referenced
                  type: string
                name:
                  description: Name is the name of resource being referenced
                  type: string
              required:
              - kind
              - name
              type: object
            snapshotCancel:
              description: SnapshotCancel indicates request to cancel ongoing snapshot.  SnapshotCancel
                can be set at anytime before the snapshot reaches a terminal phase.  If
                the snapshot has reached a terminal phase
              type: boolean
          required:
          - backupRepository
          - resourceHandle
          type: object
        status:
          description: Current status of the snapshot operation
          properties:
            message:
              description: Message is a message about the snapshot's status.
              type: string
            metadata:
              description: Metadata for the snapshotted object
              format: byte
              type: string
            phase:
              description: Phase is the current state of the Snapshot.
              type: string
            progress:
              description: Progress for the upload
              properties:
                bytesDone:
                  format: int64
                  type: integer
                totalBytes:
                  format: int64
                  type: integer
              type: object
            snapshotID:
              description: Snapshot ID that has been taken.  This will be filled in
                when the phase goes to "Snapshotted"
              type: string
          type: object
      required:
      - spec
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
