
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (unknown)
  creationTimestamp: null
  name: downloads.veleroplugin.io
spec:
  group: veleroplugin.io
  names:
    kind: Download
    listKind: DownloadList
    plural: downloads
    singular: download
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: Download describe a velero-plugin restore
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec is the custom resource spec
          properties:
            restoreTimestamp:
              description: RestoreTimestamp records the time the restore was called.
                The server's time is used for SnapshotTimestamp
              format: date-time
              type: string
            snapshotID:
              description: SnapshotID is the identifier for the snapshot of the volume.
              type: string
          type: object
        status:
          description: DownloadStatus is the current status of a Download.
          properties:
            completionTimestamp:
              description: CompletionTimestamp records the time an download was completed.
                Completion time is recorded even on failed downloads. The server's
                time is used for CompletionTimestamps
              format: date-time
              nullable: true
              type: string
            message:
              description: Message is a message about the download's status.
              type: string
            phase:
              description: Phase is the current state of the Download.
              enum:
              - New
              - InProgress
              - Completed
              - Failed
              type: string
            processingNode:
              description: The DataManager node that has picked up the Download for
                processing. This will be updated as soon as the Download is picked
                up for processing. If the DataManager couldn't process Download for
                some reason it will be picked up by another node.
              type: string
            progress:
              description: Progress holds the total number of bytes of the volume
                and the current number of restore up bytes. This can be used to display
                progress information about the restore operation.
              properties:
                bytesDone:
                  format: int64
                  type: integer
                totalBytes:
                  format: int64
                  type: integer
              type: object
            startTimestamp:
              description: StartTimestamp records the time an download was started.
                The server's time is used for StartTimestamps
              format: date-time
              nullable: true
              type: string
            volumeID:
              description: VolumeID is the identifier for the restored volume.
              type: string
          type: object
      required:
      - spec
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
